import MarketingLayout from "../marketing/MarketingLayout";

export default function Disclaimer() {
  return (
    <MarketingLayout>
      <main className="px-4 py-14">
        <div className="mx-auto max-w-5xl space-y-8">
          <div className="text-center">
            <div className="inline-flex items-center rounded-full bg-teal-50 px-4 py-1.5 text-sm font-medium text-teal-800 ring-1 ring-teal-100">
              Important Regulatory &amp; AI Disclaimer
            </div>
            <h1 className="mt-4 font-display text-3xl font-bold text-slate-900 md:text-4xl">
              Important Regulatory &amp; AI Disclaimer
            </h1>
            <p className="mt-3 text-slate-600">
              MockOfsted is a training and simulation platform. Professional judgement is required at all times. This platform carries important disclaimers regarding its use and limitations.
            </p>
          </div>

          <div className="rounded-[28px] border bg-white p-6 shadow-sm ring-2 ring-teal-200">
            <div className="max-h-[70vh] overflow-y-auto pr-2 space-y-6 text-sm text-slate-700">
              <div className="text-xs text-slate-500">
                Last updated: 11 March 2026. If you do not agree, do not use the service.
              </div>

              <Section title="1. Nature of Service">
                <p>
                  MockOfsted is a practice, simulation, and training platform designed to help childcare professionals prepare for Ofsted inspections. It is <strong>not</strong> an official Ofsted product, is not endorsed by Ofsted, and does not replace official inspection processes, professional advice, or compliance with regulatory requirements.
                </p>
              </Section>

              <Section title="2. No Guarantee of Outcomes">
                <p className="mb-3">
                  <strong>You acknowledge and accept that:</strong>
                </p>
                <ul className="list-disc space-y-2 pl-5">
                  <li>MockOfsted does NOT guarantee Ofsted ratings, judgements, grades, or inspection outcomes of any kind</li>
                  <li>Actual Ofsted inspections are conducted by qualified, trained inspectors using professional judgement and contextual evidence far beyond any software tool</li>
                  <li>Real inspection outcomes depend on complex factors including: inspectors&apos; experience, contextual knowledge of your setting, quality of physical evidence, staff interviews, child observations, and regulatory standards interpretation</li>
                  <li>Scores or feedback generated by MockOfsted may not reflect an inspector&apos;s assessment</li>
                  <li>High scores in MockOfsted do NOT guarantee a high Ofsted rating. Low scores do NOT guarantee a low rating</li>
                  <li>Improvement on MockOfsted does NOT guarantee improved Ofsted outcomes</li>
                </ul>
              </Section>

              <Section title="3. No Professional or Legal Advice">
                <p className="mb-2">
                  <strong>MockOfsted does NOT provide:</strong>
                </p>
                <ul className="list-disc space-y-2 pl-5">
                  <li>Legal advice regarding childcare regulations, employment law, or compliance</li>
                  <li>Safeguarding or child protection advice — you must consult qualified safeguarding professionals</li>
                  <li>HR, employment, or performance management advice</li>
                  <li>Medical, psychological, or developmental advice regarding children</li>
                  <li>Regulatory compliance advice — consult your local authority and official Ofsted guidance</li>
                  <li>Business, financial, or operational advice</li>
                </ul>
                <p className="mt-3">
                  All advice, guidance, and regulatory decisions must be made by qualified, accountable professionals within your setting. MockOfsted is a supplement only.
                </p>
              </Section>

              <Section title="4. AI Limitations & Errors">
                <p className="mb-3">
                  <strong>AI-generated outputs may:</strong>
                </p>
                <ul className="list-disc space-y-2 pl-5">
                  <li>Contain factual errors, inaccuracies, or misinterpretations of regulations</li>
                  <li>Miss important context or nuance specific to your setting</li>
                  <li>Provide generic feedback that does not reflect your specific circumstances</li>
                  <li>Generate responses that are inappropriate, irrelevant, or misleading</li>
                  <li>Misinterpret your question or provide off-topic answers</li>
                  <li>Reflect biases or limitations inherent in AI training data</li>
                  <li>Change between sessions or generate inconsistent feedback for similar inputs</li>
                </ul>
                <p className="mt-3">
                  <strong>You are entirely responsible for verifying, interpreting, and contextualising all AI outputs before relying on them for any decision.</strong>
                </p>
              </Section>

              <Section title="5. Human Review is Mandatory">
                <p>
                  All outputs from MockOfsted (feedback, scores, suggestions, insights) <strong>must be reviewed and validated by qualified humans</strong> within your organisation before any reliance or action. Do not treat any MockOfsted output as definitive or substitute for human professional judgement.
                </p>
              </Section>

              <Section title="6. Safeguarding Disclaimer">
                <p className="mb-3">
                  <strong>Critical:</strong> This platform cannot and must not be used as the primary basis for safeguarding decisions. Safeguarding is a serious responsibility that requires:
                </p>
                <ul className="list-disc space-y-2 pl-5">
                  <li>Qualified, accountable safeguarding professionals with relevant training and experience</li>
                  <li>Full knowledge of individual child and family circumstances</li>
                  <li>Proper documentation, evidence gathering, and multi-agency liaison</li>
                  <li>Compliance with local safeguarding policies and statutory duties</li>
                  <li>Consultation with local safeguarding boards and authorities where required</li>
                </ul>
                <p className="mt-3">
                  If you have safeguarding concerns regarding any child, contact your local safeguarding team, local authority children's services, or the NSPCC immediately. Do not rely on MockOfsted for safeguarding decisions.
                </p>
              </Section>

              <Section title="7. Regulatory Compliance">
                <p className="mb-2">
                  MockOfsted is a practice tool only. <strong>Regulatory compliance is your responsibility.</strong>
                </p>
                <ul className="list-disc space-y-2 pl-5">
                  <li>You remain fully responsible for meeting all Ofsted and regulatory requirements</li>
                  <li>You must maintain up-to-date knowledge of changes to Ofsted frameworks, SCCIF standards, and legislation</li>
                  <li>You must comply with all statutory duties including safeguarding, health and safety, employment law, and data protection</li>
                  <li>Practice on MockOfsted does not relieve you of compliance obligations</li>
                  <li>You must obtain independent professional advice and maintain proper evidence for regulatory compliance</li>
                </ul>
              </Section>

              <Section title="8. Data Quality & Accuracy">
                <p>
                  We make no representations regarding the accuracy, completeness, or currency of information provided in the Service, including Ofsted framework data, SCCIF standards summaries, or quality indicators. You are responsible for verifying information against official Ofsted publications and legislation.
                </p>
              </Section>

              <Section title="9. No Confidentiality for Child Data">
                <p className="mb-2">
                  <strong>Important:</strong> Do not submit identifiable information about children, families, or staff to MockOfsted.
                </p>
                <ul className="list-disc space-y-2 pl-5">
                  <li>While we make reasonable efforts to protect data, we cannot guarantee confidentiality once data is transmitted</li>
                  <li>Data may be processed by third-party AI providers (Anthropic Claude) to generate feedback</li>
                  <li>You remain responsible for ensuring you have authority to submit any data and that appropriate consents are in place</li>
                  <li>Submitting identifiable child data may breach GDPR, data protection laws, and safeguarding obligations</li>
                  <li>We strongly recommend anonymisation and review of data before submission</li>
                </ul>
              </Section>

              <Section title="10. No Liability for Inspection Outcomes">
                <p>
                  We accept <strong>no liability whatsoever</strong> for:
                </p>
                <ul className="list-disc space-y-2 pl-5">
                  <li>Ofsted ratings, judgements, grades, or outcomes (whether positive or negative)</li>
                  <li>Regulatory enforcement action, notices to improve, or suspension</li>
                  <li>Business loss, closure, reputational damage, or financial impact arising from inspection outcomes</li>
                  <li>Compensation claims related to inspection results or regulatory action</li>
                  <li>Loss of employment, income, or professional standing of staff members</li>
                  <li>Impact on children, families, or settings as a consequence of inspection outcomes</li>
                </ul>
              </Section>

              <Section title="11. No Liability for AI Errors">
                <p>
                  We accept <strong>no liability</strong> for errors, omissions, inaccuracies, or harms arising from AI-generated outputs, including:
                </p>
                <ul className="list-disc space-y-2 pl-5">
                  <li>Incorrect feedback, scores, or suggestions</li>
                  <li>Inappropriate or offensive AI responses</li>
                  <li>Reliance on inaccurate AI outputs leading to operational or compliance changes</li>
                  <li>Time wasted, costs incurred, or decisions made based on AI outputs</li>
                  <li>Misinterpretation of SCCIF standards or regulatory requirements</li>
                </ul>
              </Section>

              <Section title="12. User Responsibility">
                <p>
                  By using MockOfsted, you accept full responsibility for:
                </p>
                <ul className="list-disc space-y-2 pl-5">
                  <li>All compliance, safeguarding, and regulatory obligations in your setting</li>
                  <li>Verification, validation, and appropriate contextualisation of all MockOfsted outputs</li>
                  <li>Human review and professional judgement on all matters affecting children, staff, or regulatory compliance</li>
                  <li>Maintaining appropriate records, evidence, and documentation for inspection</li>
                  <li>Any decisions or actions taken based on MockOfsted feedback</li>
                  <li>Data quality and appropriateness of information submitted to the Service</li>
                  <li>Compliance with applicable laws, regulations, and our Terms of Use</li>
                </ul>
              </Section>

              <Section title="13. No Warranties">
                <p>
                  MockOfsted is provided &quot;as is&quot; and &quot;as available&quot;. We make no warranties, representations, or guarantees regarding:
                </p>
                <ul className="list-disc space-y-2 pl-5">
                  <li>Accuracy, completeness, or suitability of any information or AI outputs</li>
                  <li>Uninterrupted or error-free operation</li>
                  <li>Compatibility with your devices, systems, or workflows</li>
                  <li>Outcomes, results, or improvements in inspection performance</li>
                  <li>Security or confidentiality of data submitted</li>
                </ul>
              </Section>

              <Section title="14. Regulatory & Professional Standards">
                <p>
                  Nothing in MockOfsted replaces your obligations under:
                </p>
                <ul className="list-disc space-y-2 pl-5">
                  <li>Childcare regulations and statutory frameworks</li>
                  <li>Ofsted inspection processes and professional standards</li>
                  <li>UK GDPR and Data Protection Act 2018</li>
                  <li>Safeguarding and child protection legislation (Children Act 1989, 2004; Care Act 2014)</li>
                  <li>Health and safety law</li>
                  <li>Employment and equality law</li>
                  <li>Any relevant professional codes of conduct</li>
                </ul>
              </Section>

              <Section title="15. Changes & Updates">
                <p>
                  We reserve the right to modify, update, or discontinue MockOfsted or any part of it at any time without notice. We are not responsible for impacts of such changes on your practice or preparation.
                </p>
              </Section>

              <Section title="16. Acknowledgement">
                <p className="font-semibold text-slate-900">
                  By using MockOfsted, you acknowledge and agree that you have read this disclaimer in full, understand all limitations and disclaimers, accept all associated risks, and agree that you will rely on professional judgement and seek independent professional advice before making any compliance, safeguarding, or operational decisions.
                </p>
              </Section>

              <Section title="Questions or Concerns">
                <p>
                  If you have any questions about this disclaimer or concerns about appropriate use, contact info@mockofsted.co.uk.
                </p>
              </Section>
            </div>
          </div>
        </div>
      </main>
    </MarketingLayout>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-2">
      <h2 className="text-lg font-semibold text-slate-900">{title}</h2>
      <div className="text-sm text-slate-700">{children}</div>
    </section>
  );
}
