import { logAudit } from "@/audit/logAudit";
import type { InspectionReport, ReportBand } from "./types";

type DomainSummary = { domain: string; avg_score: number; band: ReportBand };

// Simple client-side PDF export using jspdf (must be installed).
export async function exportReportPdf(params: {
  report: InspectionReport;
  domains: DomainSummary[];
  homeName: string | null;
  sessionTitle: string | null;
  inspectionSessionId: string;
  actorId: string;
}) {
  try {
    const mod = await import("jspdf").catch(() => null);
    if (!mod || !mod.jsPDF) throw new Error("PDF export not enabled in this build");
    const { jsPDF } = mod;

    const doc = new jsPDF();
    const lineHeight = 8;
    let y = 10;

    const addLine = (text: string, bold = false) => {
      doc.setFont(undefined, bold ? "bold" : "normal");
      doc.text(text, 10, y);
      y += lineHeight;
    };

    addLine(`Inspection Report`, true);
    addLine(`Home: ${params.homeName || "N/A"}`);
    addLine(`Title: ${params.sessionTitle || "Untitled"}`);
    addLine(`Date: ${new Date(params.report.created_at).toLocaleString()}`);
    y += 4;
    addLine(`Overall band: ${params.report.overall_band}`, true);
    addLine(`Overall score: ${params.report.overall_score.toFixed(2)}`);
    y += 4;
    addLine(`Strengths:`, true);
    doc.text(params.report.strengths || "N/A", 10, y, { maxWidth: 190 });
    y += lineHeight * 3;
    addLine(`Key risks:`, true);
    doc.text(params.report.key_risks || "N/A", 10, y, { maxWidth: 190 });
    y += lineHeight * 3;
    addLine(`Recommended actions:`, true);
    doc.text(params.report.recommended_actions || "N/A", 10, y, { maxWidth: 190 });
    y += lineHeight * 3;
    addLine(`Domain breakdown:`, true);
    params.domains.forEach((d) => {
      addLine(`${d.domain}: ${d.avg_score.toFixed(2)} (${d.band})`);
    });
    y += lineHeight;
    addLine(`Generated by Voice Inspector`, false);

    doc.save(`inspection-report-${params.inspectionSessionId}.pdf`);

    logAudit({
      actorId: params.actorId,
      action: "inspection_report_exported",
      entityType: "inspection_session",
      entityId: params.inspectionSessionId,
      metadata: { overall_band: params.report.overall_band, overall_score: params.report.overall_score },
    });
  } catch (err) {
    console.warn("PDF export failed:", err);
    throw err instanceof Error ? err : new Error("PDF export not enabled in this build");
  }
}
